/**
 * *INSERT FLASHING WARNING LIGHTS*
 *
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT IT, YOUR CHANGES WILL BE OVER-WRITTEN ON BUILD.
 */
import { ApplicationRouteInformation, applicationRoutesMap, RouteNames } from "./ApplicationRouteMeta";

export const getApplicationRoute = (name: RouteNames): ApplicationRouteInformation | null => {
    return applicationRoutesMap[name] ?? null;
};