/**
 * *INSERT FLASHING WARNING LIGHTS*
 *
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT IT, YOUR CHANGES WILL BE OVER-WRITTEN ON BUILD.
 */
export interface FrameworkModule {
    fullPath: string;
    directory: string;
    exportedIocNames: string[];
    path: string;
    pathWithoutExtension: string;
    exportedNames: string[];
}

export const FrameworkModules: {
    [key: string]: FrameworkModule;
} = {
    "src/Config/AppConfiguration": {
        directory: "/Users/sam/Code/EnvusoProjects/Core/src/Config",
        exportedIocNames: ["/src/Config/AppConfiguration::AppConfiguration"],
        exportedNames: ["AppConfiguration"],
        fullPath: "/Users/sam/Code/EnvusoProjects/Core/src/Config/AppConfiguration.ts",
        pathWithoutExtension: "src/Config/AppConfiguration",
        path: "src/Config/AppConfiguration.ts"
    },
    "src/Config/AuthConfiguration": {
        directory: "/Users/sam/Code/EnvusoProjects/Core/src/Config",
        exportedIocNames: ["/src/Config/AuthConfiguration::AuthConfiguration"],
        exportedNames: ["AuthConfiguration"],
        fullPath: "/Users/sam/Code/EnvusoProjects/Core/src/Config/AuthConfiguration.ts",
        pathWithoutExtension: "src/Config/AuthConfiguration",
        path: "src/Config/AuthConfiguration.ts"
    },
    "src/Config/DatabaseConfiguration": {
        directory: "/Users/sam/Code/EnvusoProjects/Core/src/Config",
        exportedIocNames: ["/src/Config/DatabaseConfiguration::DatabaseConfiguration"],
        exportedNames: ["DatabaseConfiguration"],
        fullPath: "/Users/sam/Code/EnvusoProjects/Core/src/Config/DatabaseConfiguration.ts",
        pathWithoutExtension: "src/Config/DatabaseConfiguration",
        path: "src/Config/DatabaseConfiguration.ts"
    },
    "src/Config/FilesystemPathsConfiguration": {
        directory: "/Users/sam/Code/EnvusoProjects/Core/src/Config",
        exportedIocNames: ["/src/Config/FilesystemPathsConfiguration::FilesystemPathsConfiguration"],
        exportedNames: ["FilesystemPathsConfiguration"],
        fullPath: "/Users/sam/Code/EnvusoProjects/Core/src/Config/FilesystemPathsConfiguration.ts",
        pathWithoutExtension: "src/Config/FilesystemPathsConfiguration",
        path: "src/Config/FilesystemPathsConfiguration.ts"
    },
    "src/Config/SerializationConfiguration": {
        directory: "/Users/sam/Code/EnvusoProjects/Core/src/Config",
        exportedIocNames: ["/src/Config/SerializationConfiguration::SerializationConfiguration"],
        exportedNames: ["SerializationConfiguration"],
        fullPath: "/Users/sam/Code/EnvusoProjects/Core/src/Config/SerializationConfiguration.ts",
        pathWithoutExtension: "src/Config/SerializationConfiguration",
        path: "src/Config/SerializationConfiguration.ts"
    },
    "src/Config/ServerConfiguration": {
        directory: "/Users/sam/Code/EnvusoProjects/Core/src/Config",
        exportedIocNames: ["/src/Config/ServerConfiguration::ServerConfiguration"],
        exportedNames: ["ServerConfiguration"],
        fullPath: "/Users/sam/Code/EnvusoProjects/Core/src/Config/ServerConfiguration.ts",
        pathWithoutExtension: "src/Config/ServerConfiguration",
        path: "src/Config/ServerConfiguration.ts"
    },
    "src/Config/ServicesConfiguration": {
        directory: "/Users/sam/Code/EnvusoProjects/Core/src/Config",
        exportedIocNames: ["/src/Config/ServicesConfiguration::ServicesConfiguration"],
        exportedNames: ["ServicesConfiguration"],
        fullPath: "/Users/sam/Code/EnvusoProjects/Core/src/Config/ServicesConfiguration.ts",
        pathWithoutExtension: "src/Config/ServicesConfiguration",
        path: "src/Config/ServicesConfiguration.ts"
    },
    "src/Config/SessionConfiguration": {
        directory: "/Users/sam/Code/EnvusoProjects/Core/src/Config",
        exportedIocNames: ["/src/Config/SessionConfiguration::SessionConfiguration"],
        exportedNames: ["SessionConfiguration"],
        fullPath: "/Users/sam/Code/EnvusoProjects/Core/src/Config/SessionConfiguration.ts",
        pathWithoutExtension: "src/Config/SessionConfiguration",
        path: "src/Config/SessionConfiguration.ts"
    },
    "src/Config/StorageConfiguration": {
        directory: "/Users/sam/Code/EnvusoProjects/Core/src/Config",
        exportedIocNames: ["/src/Config/StorageConfiguration::StorageConfiguration"],
        exportedNames: ["StorageConfiguration"],
        fullPath: "/Users/sam/Code/EnvusoProjects/Core/src/Config/StorageConfiguration.ts",
        pathWithoutExtension: "src/Config/StorageConfiguration",
        path: "src/Config/StorageConfiguration.ts"
    },
    "src/Config/WebsocketsConfiguration": {
        directory: "/Users/sam/Code/EnvusoProjects/Core/src/Config",
        exportedIocNames: ["/src/Config/WebsocketsConfiguration::WebsocketsConfiguration"],
        exportedNames: ["WebsocketsConfiguration"],
        fullPath: "/Users/sam/Code/EnvusoProjects/Core/src/Config/WebsocketsConfiguration.ts",
        pathWithoutExtension: "src/Config/WebsocketsConfiguration",
        path: "src/Config/WebsocketsConfiguration.ts"
    }
};